import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Red_Hat_Display, Epilogue  } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'],
  variable: '--font-poppins',
})

const redHat = Red_Hat_Display({
  subsets: ['latin'],
  weight: ['300','400','500','600','700','800','900'],
  variable: '--font-redhat',
})

const epilogue = Epilogue({
  subsets: ['latin'],
  weight: ['300','400','500','600','700','800','900'],
  variable: '--font-epilogue',
})

const clashDisplay = localFont({
  src: [
    {
      path: "./fonts/ClashDisplay-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-clash",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${redHat.variable} ${epilogue.variable} ${clashDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
